//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuildingManagementProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Apartment
    {
        public string ApartmentId { get; set; }
        public string BuildingId { get; set; }
        public int ApartmentNumber { get; set; }
        public int Rooms { get; set; }
        public decimal Price { get; set; }
        public string Status { get; set; }
        public string Description { get; set; }
        public string TenantId { get; set; }
    
        public virtual Building Building { get; set; }
        public virtual Tenant Tenant { get; set; }
    }
}
